model_name: flux-dev
data_config:
  train_batch_size: 8
  num_workers: 6
  img_size: 256
  dataset_name: McGill-NLP/AURORA
  split: train
report_to: wandb
train_batch_size: 8
output_dir: output_aurora/
max_train_steps: 100000
learning_rate: 2e-5
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 100
checkpoints_total_limit: 10
tracker_project_name: flux-aurora
resume_from_checkpoint: latest
gradient_accumulation_steps: 2
